version: "3.7"
services:
  envoy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    image: distributed-envoy
    ports:
      - "8080:8080"
    links:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: distributed-backend
    ports:
      - "9090:9090"

  grpc-gen:
    build:
      context: .
      dockerfile: Dockerfile
    image: distributed-grpc-gen
    volumes:
      - ./backend/api:/app/api
      - ./frontend/src/jsclient:/app/jsclient
