/**
 * @fileoverview gRPC-Web generated client stub for runner
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.1
// source: runner/runner.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.runner = require('./runner_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.runner.RunnerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.runner.RunnerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.runner.RunRequest,
 *   !proto.runner.NodeData>}
 */
const methodDescriptor_Runner_runAlgo = new grpc.web.MethodDescriptor(
  '/runner.Runner/runAlgo',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.runner.RunRequest,
  proto.runner.NodeData,
  /**
   * @param {!proto.runner.RunRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.runner.NodeData.deserializeBinary
);


/**
 * @param {!proto.runner.RunRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.runner.NodeData>}
 *     The XHR Node Readable Stream
 */
proto.runner.RunnerClient.prototype.runAlgo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/runner.Runner/runAlgo',
      request,
      metadata || {},
      methodDescriptor_Runner_runAlgo);
};


/**
 * @param {!proto.runner.RunRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.runner.NodeData>}
 *     The XHR Node Readable Stream
 */
proto.runner.RunnerPromiseClient.prototype.runAlgo =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/runner.Runner/runAlgo',
      request,
      metadata || {},
      methodDescriptor_Runner_runAlgo);
};


module.exports = proto.runner;

